GET http://localhost:3000/movies/

###

POST http://localhost:3000/movies/
Content-Type: application/json

{
    "directorId": 6,
    "movieName": "Jurassic Park",
    "leadActor": "jeff Goldblum"
}

###
GET http://localhost:3000/movies/1/


###

PUT http://localhost:3000/movies/15/
Content-Type: application/json

###

DELETE http://localhost:3000/movies/5/


###

GET http://localhost:3000/directors/


###

GET http://localhost:3000/directors/6/movies/